name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Cask setup
      run: ./test-startup.sh
    - name: Test with cask
      run: cask exec emacs -Q -batch -L . -l create-link-test.el -f ert-run-tests-batch-and-exit
    - uses: leotaku/elisp-check@master
      with:
        file: create-link.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
